### PR TITLE
Update bundle

### PR DESCRIPTION
**Pull request by ericpre**
- update hyperspy minimum requirement
- remove spyder 4.* requirement
- use dask <2021.04.0 - see https://github.com/dask/dask/issues/7583

### CODE REVIEW

**Comment by magnunor** [comment]
This is for making a new HyperSpy bundle due to the 1.6.3 release? Is it by any chance a possibility to wait with the release for an hour or two? Really tempting to have a small Atomap release, since we have a big digital workshop in 1.5 weeks.

**Comment by ericpre** [comment]
Yes, sure, please put a message here when it is done and we can re-run the build.

**Comment by magnunor** [comment]
The `pypi` version is finished. Just waiting for the conda-feedstock to finish: https://github.com/conda-forge/atomap-feedstock/pull/9

**Comment by magnunor** [comment]
The conda forge version is also finished now. So the build can be re-run.

**Comment by ericpre** [comment]
OK, the packages from the conda-forge channel usually take one hour after being uploaded to the anaconda server, because they need to be transfered to CDN servers. Also, I need to add a comment in this PR and I will do this later today at the same time!

**Pull request merged**
