### PR TITLE
Release 2022 04

### PR DESCRIPTION
**Pull request by ericpre**
- [x] Update library version, add abtem and ovito
- [x] update winpython version
- [x] tidy up workflow 

This is still pending the pyxem package on conda-forge.

### CODE REVIEW

**Comment by magnunor** [comment]
The new pyxem version is now on `conda-forge`: https://github.com/pyxem/pyxem/issues/788#issuecomment-1114024760

**Comment by hakonanes** [comment]
Thanks a lot for making this release, @ericpre. I know people, at least at NTNU, who use it as the primary way for installing kikuchipy.

Quick question: why are the kikuchipy tests not run, but lumispy's and pyxem's are?

**Comment by hakonanes** [comment]
And perhaps the newly added packages should be listed in the README?

**Comment by ericpre** [comment]
> Quick question: why are the kikuchipy tests not run, but lumispy's and pyxem's are?

The test suite fails.

**Comment by hakonanes** [comment]
> The test suite fails.

Right, good enough reason to skip. (The two failing tests part of the release version are fixed in the development branch.)

**Pull request merged**
