### PR TITLE
Add conda build

### PR DESCRIPTION
**Pull request by ericpre**
Add conda based distributions build with constructor for linux, macosx and windows. All the build are done on azure and the installers can be downloaded from there. These includes the package defined in `conda_distribution/construct.yaml`.

The Winpython based distribution is kept on appveyor.

### CODE REVIEW

**Comment by ericpre** [comment]
This PR depends on an external repository https://github.com/ericpre/CI to setup the azure and travis. This is experimental at the moment and not documented but it seems to work well. Once we are happy with the design, I would suggest to move it to the hyperspy organisation and start using it for other libraries. The idea is to simplify setting up and updating the different CIs but also to be consistent across different libraries, which should be very useful for the split.

The last build is available at:
https://dev.azure.com/ericpre/hyperspy-bundle/_build/results?buildId=120&view=logs

and the installers can be downloaded using the "artefacts" blue button in the two right corner.

**Comment by MGRashed** [comment]
Leaving a comment to support this initiative. Many of us already use Anaconda distribution, this will help to reduce python distribution clutter on Windows.

**Comment by ericpre** [comment]
@MGRashed: you can try to download the following bundle:
https://github.com/ericpre/hyperspy-bundle/releases/tag/2020.01.18

I have tested on several windows and linux machine and it worked very well (MacOSX only a few machine). If you test it, feedback is more than welcome.

**Comment by MGRashed** [comment]
@ericpre: I have installed it in my Windows 10 x64 laptop (Thinkpad x230). No trace of hyperspy was found afterwards (only Coda menu is seen in Programs), and my external monitor is losing signals periodically since then (graphics issue?).

**Comment by MGRashed** [comment]
@ericpre: I have always used HyperSpy through the UI, not through jupyter notebook. That's what I meant by no trace. Is the GUI not supported yet?

**Comment by ericpre** [comment]
OK, indeed the shortcut is not there yet! Actually, this is not related to this installer really, this is the hyperspyui recipe which needs to be updated!
In the mean time, you can start HyperSpyUI from the anaconda prompt and execute `hyperspyui` to start it.

On a side note, the "recommended" use of HyperSpy is with the notebook rather with HyperSpyUI, mainly because the later only have a limited number of HyperSpy features. For info, HyperSPy in the notebook also have some GUI bits.

**Comment by MGRashed** [comment]
> On a side note, the "recommended" use of HyperSpy is with the notebook rather with HyperSpyUI, mainly because the later only have a limited number of HyperSpy features. For info, HyperSPy in the notebook also have some GUI bits.

Yes I know, but my usage are basic stuff. Hopefully hyperspyui recipe will be updated soon, and we will have same experience as with the WinPython distro. :)

**Comment by francisco-dlp** [comment]
> and we will have same experience as with the WinPython distro. :)

That's a good point. As the bundle is intended for newbies, transitioning from WP to this should be as smooth as possible, ideally the users shouldn't be able to notice the difference.

**Comment by ericpre** [comment]
> That's a good point. As the bundle is intended for newbies, transitioning from WP to this should be as smooth as possible, ideally the users shouldn't be able to notice the difference.

True: https://github.com/conda-forge/hyperspyui-feedstock/pull/2

**Comment by ericpre** [comment]
@MGRashed: do you want to have another go?
https://github.com/ericpre/hyperspy-bundle/releases/tag/2020.01.26

**Comment by MGRashed** [comment]
Checked, seems to be working as before. Thank you.

**Comment by ericpre** [comment]
Great, thanks for the confirmation!

**Comment by MGRashed** [comment]
I think it would be better to group Hyperspy and Anaconda libraries separately, e.g. two separate start menu shortcuts, and two separate installation program directory. Anacona is widely used for other applications, so maybe a pre-installation check to skip anaconda distro if its already installed in the system.

**Comment by ericpre** [comment]
> I think it would be better to group Hyperspy and Anaconda libraries separately, e.g. two separate start menu shortcuts, and two separate installation program directory. Anacona is widely used for other applications, so maybe a pre-installation check to skip anaconda distro if its already installed in the system.

The purpose of the hyperspy-bundle is to install hyperspy, hyperspyui etc. *and* a python distribution at the same time.
If you want to install hyperspyui only, you need to run `conda install hyperspyui -c conda-forge` from the anaconda prompt or `pip install hyperspyui` from any other python distribution. The hyperspyui documentation needs improvement to mention installation from anaconda/miniconda distribution.

**Comment by ericpre** [comment]
xref clarify installation of hyperspyui in anaconda: https://github.com/hyperspy/hyperspyUI/pull/191

**Comment by ericpre** [comment]
I have this installer at the workshop at ACMM and it worked very well for everyone. @francisco-dlp, do you think we could try to use this installer for the workshop at Diamond?
I would be keen to do that because this is a good opportunity to test it further and if there are issues we can sort them out fairly quickly or fall back to previous installer.

**Comment by ericpre** [comment]
Close in favour of #44.

**Pull request closed without merging**
