### PR TITLE
Release with py37

### LINKED ISSUE #23: Build with Winpython 1.10 (2018-01): long path issue
Winpython 1.10 (2018-01) includes a working version of jupyterLab but comes at the cost of installation only possible in a folder with a full path ~< 37 characters... because the maximum length of file path on windows if about ~260 characters and npm which is the javascript package manager (required for jupyterLab), has a deeply nested folder structure...
See https://groups.google.com/forum/#!topic/winpython/jkL90WJ2cbw

Although this would be great to have the jupyterLab working in the bundle installer, this is quite annoying to have to restrict its installation to folders with a path length ~< 37 characters...

### LINKED ISSUE #31: HyperSpy Bundle 2018.09.04: HyperSpyUI is not opening
As reported in the gitter room: HyperSpy UI, Jupyter notebook and Spyder IDE are not opening (command prompt exits abruptly). The system is Windows 7 x64.

### PR DESCRIPTION
**Pull request by ericpre**
Same as #33 but with python 3.7.

- [x] update to last winpython,
- [x] set tqdm version to 4.24 to avoid issue with https://github.com/hyperspy/hyperspy/issues/2077,
- [x] replace python 3.5 with 3.7,
- [x] remove typing package to avoid python 3.7, see https://ci.appveyor.com/project/ericpre/hyperspy-bundle/builds/19660402,
- [x] fix #23,
- [x] fix #31,
- [x] ready for review.

### CODE REVIEW

**Comment by francisco-dlp** [comment]
Since the new WP version contains JupyterLab, wouldn't it be good to add a Jupyter Lab entry in the Start Menu alongside the current Notebook and Console entries?

**Comment by ericpre** [comment]
Yes, it would be good, but at the same time, we need to check that the matplotlib backend are working properly and also add the corresponding documentation.
I think we need to release a bundle quickly first and then work on jupyterlab.

**Comment by ericpre** [comment]
I may have been pessimistic and it seems that the jupyter lab is working out of the box and `%matplotlib widget` to get the notebook backend is working fine. I will give a go.

**Comment by ericpre** [comment]
For the last build with the shortcut for jupyter lab in the start menu and the context menu: https://ci.appveyor.com/project/ericpre/hyperspy-bundle/builds/19764021

**Comment by ericpre** [comment]
I have testing the installation on windows 7 with the different installation mode and it works as expected. @francisco-dlp, could you finish the review and merge this and then we make the release from this repository?

**Comment by francisco-dlp** [comment]
LGTM

**Pull request merged**
