### PR TITLE
New release

### PR DESCRIPTION
**Pull request by ericpre**
* Add jupyter shortcut in context menu for single users for installation without admin right,
* update to last winpython distribution,
* clean cache (*pyc) before uninstallation, so there is no left over files.
* remove tensorflow and torch to get below the 2Go limit of NSIS.
* include atomap, pixstem and pyxem
* run test suite for atomap and pyxem

This is pending a HyperSpyUI release because of the pyqt 5.12 icon issue.

### CODE REVIEW

**Comment by ericpre** [comment]
Build available at https://github.com/ericpre/hyperspy-bundle/releases/tag/2019-06-19

**Comment by francisco-dlp** [comment]
LGTM, except for the removal of tensorflow and torch. Would it be possible to use [nsisbi](https://sourceforge.net/projects/nsisbi/) instead?

**Comment by ericpre** [comment]
Yes, it is possible to use nsisbi, which is a fork of nsis and not a plugin. It doesn't seem to be widely used at the moment and one concern may be that it is not mature (according to the author, this is the reason why it is still a fork and not merged with nsis yet). It also means that it hasn't been tested by a large user base.

In any case, It seems to work but it would need testing:
Installers are available at https://ci.appveyor.com/project/ericpre/hyperspy-bundle/builds/25972606

I could do test it in different windows system int the next few days and if it works fine, I would be fine to go for this option.

**Comment by francisco-dlp** [comment]
Sounds great!

**Comment by ericpre** [comment]
The "administrator rights elevation" doesn't work with NSISBI: the all users install only works if started with admin right.
The UAC plugin is deprecated, so it would be good to remove it and revisit using NSISBI in the future.

Relevant links:
https://nsis.sourceforge.io/UAC_plug-in
https://stackoverflow.com/questions/18990418/how-can-i-switch-between-requiring-and-not-requiring-admin-permission-in-nsis

**Pull request merged**
